swagger: '2.0'
info:
  title: PROMIS API
  description: Development version, a subject to change
  version: "1.0.0"

# the domain of the service
# (to be changed by deploy?)
host: api.promis

# array of all schemes that your API supports
schemes:
  - http  # for easier testing
  - https

# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /projects:
    x-swagger-router-controller: ProjectsView
    get:
      summary: Space projects
      description: |
        This endpoint returns information about available space projects
        and their duration.
      tags:
        - Projects
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /devices:
    x-swagger-router-controller: DevicesView
    get:
      summary: Satellite devices
      description: |
        The Sattelite Devices endpoint returns a list of available devices
        installed on the specific satellite (used in particular space project).
      tags:
        - Projects
      parameters:
        - name: project_id
          in: query
          description: Project ID to query its satellite devices for
          required: true
          type: number
      responses:
        200:
          description: An array of available devices
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /sessions:
    x-swagger-router-controller: SessionsView
    get:
      summary: Measurement sessions
      description: |
        This endpoint allows to get info about available sessions of a satellite (when it was able to gather the data)
      tags:
        - Measurements
      parameters:
        - name: project_id
          in: query
          description: Project ID to query its sessions for
          required: true
          type: number
      responses:
        200:
          description: An array of available sessions
          schema:
            type: array
            items:
              $ref: '#/definitions/Session'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # more measurement-related endpoints to be added here...

  /quicklook:
    x-swagger-router-controller: QuicklookView
    get:
      summary: Get a quicklook of data
      description: |
        This endpoint allows to get a quicklook of certain data measurement.
      tags:
        - Measurements
      responses:
        200:
          description: Quicklook data
          schema:
            $ref: '#/definitions/Quicklook'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Project:
    type: object
    properties:
      id:
        type: number
        description: Unique project ID
      name:
        type: string
        description: Name of the project
      desc:
        type: string
        description: Description of the project
      timelapse:
        $ref: '#/definitions/Time'

  Device:
    type: object
    properties:
      id:
        type: number
        description: Unique device ID
      name:
        type: string
        description: Short name of the device
      desc:
        type: string
        description: Detailed info about the device

  Session:
    type: object
    properties:
      id:
        type: number
        description: Unique session ID
      orbit:
        type: number
        description: Orbit representation
      time:
        $ref: '#/definitions/Time'

  Quicklook:
    type: object
    properties:
      data:
        type: string
        description: Quicklook data


  # helper objects next

  Time:
    type: object
    properties:
      begin:
        type: string
      end:
        type: string

  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message
