swagger: '2.0'
info:
  title: Promis API
  description: Development version, a subject to change
  version: "0.1.2"

# the domain of the service
# (to be changed by deploy)
host: ${conf.promis_origin}

# array of all schemes that your API supports
schemes:
  - http  # for easier testing
  - https

# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded

produces:
  - application/json

paths:
  # Space projects
  /projects:
    x-swagger-router-view: ProjectsView
    get:
      operationId: ListProjects
      summary: Space projects
      tags:
        - Projects
      description: |
        This endpoint returns information about available space projects and their duration.
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /projects/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ProjectsView
    get:
      operationId: GetProject
      summary: Space project
      tags:
        - Projects
      description: |
        Retrieve particular space project
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Space project
          schema:
            $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Satellite devices
  /devices:
    x-swagger-router-view: DevicesView
    get:
      operationId: ListDevices
      summary: Satellite devices
      tags:
        - Devices
      description: |
        The Sattelite Devices endpoint returns a list of available devices
        installed on the specific satellite (used in particular space project).
      parameters:
        - name: project
          in: query
          description: Project ID to query its satellite devices for
          type: integer
      responses:
        200:
          description: An array of available devices
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /devices/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: DevicesView
    get:
      operationId: GetDevice
      summary: Satellite device
      tags:
        - Devices
      description: |
        Get particular satellite device
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Satellite device
          schema:
            $ref: '#/definitions/Device'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Satellite channels
  /channels:
    x-swagger-router-view: ChannelsView
    get:
      operationId: ListChannels
      summary: Satellite channels
      tags:
        - Channels
      description: |
        The Sattelite Channels endpoint returns a list of available channels
        related to some specific parameters
      parameters:
        - name: project
          in: query
          description: Project ID to query its satellite channels for
          type: integer
      responses:
        200:
          description: An array of available channels
          schema:
            type: array
            items:
              $ref: '#/definitions/Channel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /channels/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ChannelsView
    get:
      operationId: GetChannel
      summary: Satellite channel
      tags:
        - Channels
      description: |
        Get particular channel
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Satellite channel
          schema:
            $ref: '#/definitions/Channel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Measurement sessions
  /sessions:
    x-swagger-router-view: SessionsView
    get:
      operationId: ListSessions
      summary: Measurement sessions
      tags:
        - Measurements
        - Sessions
      description: |
        This endpoint allows to get info about available sessions of a satellite (when it was able to gather the data)
      parameters:
        - name: project
          in: query
          description: Project ID to query its sessions for
          type: integer
        - name: fromtime
          in: query
          description: From time, UNIX timestamp at UTC
          type: integer
        - name: totime
          in: query
          description: To time, UNIX timestamp at UTC
          type: integer
        - name: polygon
          description: WKT polygon with desired search area
          in: query
          type: string
      responses:
        200:
          description: An array of available sessions
          schema:
            type: array
            items:
              $ref: '#/definitions/IdURL'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sessions/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: SessionsView
    get:
      operationId: GetSession
      summary: Measurement session
      tags:
        - Measurements
        - Sessions
      description: |
        Retrieve single session
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Measurement session
          schema:
            $ref: '#/definitions/Session'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Measurements itself
  /measurements:
    x-swagger-router-view: MeasurementsView
    get:
      operationId: ListMeasurements
      summary: Measurements
      tags:
        - Measurements
      description: |
        Get list of measurements
      parameters:
        - name: session
          description: Desired session ID(s)
          in: query
          type: array
          items:
            type: integer
        - name: parameter
          description: Desired parameter ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: channel
          description: Desired channel ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: minfreq
          type: integer
          in: query
        - name: maxfreq
          type: integer
          in: query
      responses:
        200:
          description: An array of measurements
          schema:
            type: array
            items:
              $ref: '#/definitions/Measurement'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /measurements/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: MeasurementsView
    get:
      operationId: GetMeasurement
      summary: Measurement
      tags:
        - Measurements
      description: |
        Get particular measurement
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Measurement
          schema:
            $ref: '#/definitions/Measurement'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Parameters
  /parameters/:
    x-swagger-router-view: ParametersView
    get:
      operationId: ListParameters
      summary: Parameters
      tags:
        - Parameters
      description: |
        Get list of parameters
      parameters:
        - name: channel
          description: Desired channel ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: minfreq
          type: integer
          in: query
        - name: maxfreq
          type: integer
          in: query
      responses:
        200:
          description: An array of parameters
          schema:
            type: array
            items:
              $ref: '#/definitions/Parameter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /parameters/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ParametersView
    get:
      operationId: GetParameter
      summary: Parameter
      tags:
        - Parameters
      description: |
        Get particular parameter
      parameters:
        - $ref: '#/parameters/Id'
      responses:
        200:
          description: Parameter
          schema:
            $ref: '#/definitions/Parameter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # TODO: here and below, add /channel and /parameter paths
  # TODO: reuse parameters across several paths
  # Quicklook
  /quicklook/{id}/{source}:
    x-swagger-object-key: id
    x-swagger-router-view: QuicklookView
    get:
      operationId: Quicklook
      summary: Get a quicklook of data
      tags:
        - Measurements
      description: |
        This endpoint allows to get a quicklook of certain data measurement.
      parameters:
        - $ref: '#/parameters/Id'
        - $ref: '#/parameters/Source'
        - $ref: '#/parameters/FromTime'
        - $ref: '#/parameters/ToTime'
        # TODO: in future release
        - $ref: '#/parameters/Polygon'
        - name: points
          in: query
          type: integer
          required: false
          description: Amount of data points to show on the quicklook.
      responses:
        200:
          description: Quicklook data
          schema:
            $ref: '#/definitions/Quicklook'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Data download
  /download/{id}/{source}:
    x-swagger-object-key: id
    x-swagger-router-view: DownloadView
    get:
      operationId: Download
      summary: Download data
      tags:
        - Measurements
      description: |
        This endpoint allows to get a quicklook of certain data measurement.
      parameters:
        - $ref: '#/parameters/Id'
        - $ref: '#/parameters/Source'
        - $ref: '#/parameters/FromTime'
        - $ref: '#/parameters/ToTime'
        # TODO: in future release
        - $ref: '#/parameters/Polygon'
        # TODO: - required not working - put it on the deeper links
        - name: fmt
          in: query
          type: string
          required: false
          description: Format name to download data in.
          default: json
          enum:
            - json
            - ascii
            - csv
            - netcdf
      responses:
        200:
          description: Raw data
          schema:
            $ref: '#/definitions/RawData'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

# return objects
definitions:
  Project:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
      name:
        type: string
        description: Short name
      desc:
        type: string
        description: In-depth description
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- $ref: '#/definitions/NameDesc'
      #- properties:
      timelapse:
        $ref: '#/definitions/Time'

  Device:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
      name:
        type: string
        description: Short name
      desc:
        type: string
        description: In-depth description
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- $ref: '#/definitions/NameDesc'
      #- properties:
      channels:
        type: array
        description: Channels the device provides
        items:
          $ref: '#/definitions/IdURL'

  Channel:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
      name:
        type: string
        description: Short name
      desc:
        type: string
        description: In-depth description
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- $ref: '#/definitions/NameDesc'

  Parameter:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
      name:
        type: string
        description: Short name
      desc:
        type: string
        description: In-depth description
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- $ref: '#/definitions/NameDesc'
      #- properties:
      channel:
            #allOf:
              #- description: Channel the parameter depends on
              #- $ref: '#/definitions/IdURL'
        $ref: '#/definitions/IdURL'

  Session:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- properties:
          #project:
            #type: integer
            #description: Related project ID
          #orbit:
            #type: number
            #description: Orbit representation
          #geoline:
            #$ref: '#/definitions/GeoLine'
          #measurements:
            #type: array # api links to measurement instances
            #description: Available measurements for this session
            #items:
              #$ref: '#/definitions/IdURL'
          #timelapse:
            #$ref: '#/definitions/Time'
        project:
          type: integer
          description: Related project ID
        orbit:
          type: number
          description: Orbit representation
        geoline:
          $ref: '#/definitions/GeoLine'
        measurements:
          type: array # api links to measurement instances
          description: Available measurements for this session
          items:
            $ref: '#/definitions/IdURL'
        timelapse:
          $ref: '#/definitions/Time'


  Measurement:
    type: object
    # cut here, #193
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API
    #allOf:
      #- $ref: '#/definitions/IdURL'
      #- properties:
          #session:
            #$ref: '#/definitions/IdURL'
          #channel:
            #$ref: '#/definitions/IdURL'
          #parameter:
            #$ref: '#/definitions/IdURL'
          #freq:
            #type: number
            #description: Sampling frequency
          #min_freq:
            #type: number
          #max_freq:
            #type: number
          #channel_quicklook:
            #type: string
            #description: URL to channel quicklook
          #channel_download:
            #type: string
            #description: URL to channel data download
          #parameter_quicklook:
            #type: string
            #description: URL to parameter quicklook
          #parameter_download:
            #type: string
            #description: URL to parameter data download
        session:
          $ref: '#/definitions/IdURL'
        channel:
          $ref: '#/definitions/IdURL'
        parameter:
          $ref: '#/definitions/IdURL'
        freq:
          type: number
          description: Sampling frequency
        min_freq:
          type: number
        max_freq:
          type: number
        channel_quicklook:
          type: string
          description: URL to channel quicklook
        channel_download:
          type: string
          description: URL to channel data download
        parameter_quicklook:
          type: string
          description: URL to parameter quicklook
        parameter_download:
          type: string
          description: URL to parameter data download

  Quicklook:
    type: object
    properties:
      data:
        type: array
        description: Quicklook data
      geoline:
        $ref: '#/definitions/GeoLine'
      timelapse:
        $ref: '#/definitions/Time'
      source:
        # TODO: technically it can also be a parameter but whatever
        $ref: '#/definitions/Channel'
      value:
        $ref: '#/definitions/Value'

  RawData:
    type: object
    properties:
      data:
        type: string
        description: Raw data

  # Time interval
  Time:
    type: object
    properties:
      start:
        type: integer
        description: UNIX time at UTC
      end:
        type: integer
        description: UNIX time at UTC

  # Physical value
  Value:
    type: object
    properties:
      name:
        type: string
      symbol:
        type: string
        description: The symbol or the letter used to denote the value
      units:
        type: string
        description: The abbreviated form of the units the value is measured in

  # 3D geoline
  GeoLine:
    type: array
    items:
      type: array
      description: Coordinates at 1 Hz
      items:
        type: number
        description: Latitude, Longitude, Altitude

  # Error message
  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message

  # Common components
  IdURL:
    properties:
      id:
        type: number
        description: Unique numberic identifier
      url:
        type: string
        description: URL location within API

  NameDesc:
    properties:
      name:
        type: string
        description: Short name
      desc:
        type: string
        description: In-depth description

parameters:
  Id:
    name: id
    in: path
    type: integer
    required: true
    description: Unique numerical identifier

  Source:
    name: source
    in: path
    type: string
    description: Where to take the data from
    required: true
    enum:
      - parameter
      - channel

  FromTime:
    name: fromtime
    in: query
    description: From time, UNIX timestamp at UTC
    type: integer

  ToTime:
    name: totime
    in: query
    description: To time, UNIX timestamp at UTC
    type: integer

  Polygon:
    name: polygon
    description: WKT polygon with desired search area
    in: query
    type: string

