swagger: '2.0'
info:
  title: Promis API
  description: Development version, a subject to change
  version: "0.1.1"

# the domain of the service
# (to be changed by deploy)
host: ${conf.promis_origin}

# array of all schemes that your API supports
schemes:
  - http  # for easier testing
  - https

# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded

produces:
  - application/json

paths:
  # Space projects
  /projects:
    x-swagger-router-view: ProjectsView
    get:
      operationId: ListProjects
      summary: Space projects
      tags:
        - Projects
      description: |
        This endpoint returns information about available space projects and their duration.
      responses:
        200:
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /projects/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ProjectsView
    get:
      operationId: GetProject
      summary: Space project
      tags:
        - Projects
      description: |
        Retrieve particular space project
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Project ID
      responses:
        200:
          description: Space project
          schema:
            $ref: '#/definitions/Project'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Satellite devices
  /devices:
    x-swagger-router-view: DevicesView
    get:
      operationId: ListDevices
      summary: Satellite devices
      tags:
        - Devices
      description: |
        The Sattelite Devices endpoint returns a list of available devices
        installed on the specific satellite (used in particular space project).
      parameters:
        - name: project
          in: query
          description: Project ID to query its satellite devices for
          type: integer
      responses:
        200:
          description: An array of available devices
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /devices/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: DevicesView
    get:
      operationId: GetDevice
      summary: Satellite device
      tags:
        - Devices
      description: |
        Get particular satellite device
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: Device ID
      responses:
        200:
          description: Satellite device
          schema:
            $ref: '#/definitions/Device'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Satellite channels
  /channels:
    x-swagger-router-view: ChannelsView
    get:
      operationId: ListChannels
      summary: Satellite channels
      tags:
        - Channels
      description: |
        The Sattelite Channels endpoint returns a list of available channels
        related to some specific parameters
      parameters:
        - name: project
          in: query
          description: Project ID to query its satellite channels for
          type: integer
      responses:
        200:
          description: An array of available channels
          schema:
            type: array
            items:
              $ref: '#/definitions/Channel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /channels/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ChannelsView
    get:
      operationId: GetChannel
      summary: Satellite channel
      tags:
        - Channels
      description: |
        Get particular channel
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Channel ID
      responses:
        200:
          description: Satellite channel
          schema:
            $ref: '#/definitions/Channel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Measurement sessions
  /sessions:
    x-swagger-router-view: SessionsView
    get:
      operationId: ListSessions
      summary: Measurement sessions
      tags:
        - Measurements
        - Sessions
      description: |
        This endpoint allows to get info about available sessions of a satellite (when it was able to gather the data)
      parameters:
        - name: project
          in: query
          description: Project ID to query its sessions for
          type: integer
        - name: fromtime
          in: query
          description: From time
          type: string
        - name: totime
          in: query
          description: To time
          type: string
        - name: polygon
          description: Geo polygon with desired search area
          in: query
          type: string
      responses:
        200:
          description: An array of available sessions
          schema:
            type: array
            items:
              $ref: '#/definitions/Session'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sessions/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: SessionsView
    get:
      operationId: GetSession
      summary: Measurement session
      tags:
        - Measurements
        - Sessions
      description: |
        Retrieve single session
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Session ID
      responses:
        200:
          description: Measurement session
          schema:
            $ref: '#/definitions/Session'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Measurements itself
  /measurements:
    x-swagger-router-view: MeasurementsView
    get:
      operationId: ListMeasurements
      summary: Measurements
      tags:
        - Measurements
      description: |
        Get list of measurements
      parameters:
        - name: session
          description: Desired session ID(s)
          in: query
          type: array
          items:
            type: integer
        - name: parameter
          description: Desired parameter ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: channel
          description: Desired channel ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: minfreq
          type: integer
          in: query
        - name: maxfreq
          type: integer
          in: query
      responses:
        200:
          description: An array of measurements
          schema:
            type: array
            items:
              $ref: '#/definitions/Measurement'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /measurements/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: MeasurementsView
    get:
      operationId: GetMeasurement
      summary: Measurement
      tags:
        - Measurements
      description: |
        Get particular measurement
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Measurement ID
      responses:
        200:
          description: Measurement
          schema:
            $ref: '#/definitions/Measurement'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Parameters
  /parameters/:
    x-swagger-router-view: ParametersView
    get:
      operationId: ListParameters
      summary: Parameters
      tags:
        - Parameters
      description: |
        Get list of parameters
      parameters:
        - name: channel
          description: Desired channel ID(s)
          type: array
          in: query
          items:
            type: integer
        - name: minfreq
          type: integer
          in: query
        - name: maxfreq
          type: integer
          in: query
      responses:
        200:
          description: An array of parameters
          schema:
            type: array
            items:
              $ref: '#/definitions/Parameter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /parameters/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: ParametersView
    get:
      operationId: GetParameter
      summary: Parameter
      tags:
        - Parameters
      description: |
        Get particular parameter
      parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: Parameter ID
      responses:
        200:
          description: Parameter
          schema:
            $ref: '#/definitions/Parameter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Quicklook
  /quicklook/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: QuicklookView
    get:
      operationId: Quicklook
      summary: Get a quicklook of data
      tags:
        - Measurements
      description: |
        This endpoint allows to get a quicklook of certain data measurement.
      parameters:
        - name: id
          in: path
          type: string
          required: true

      responses:
        200:
          description: Quicklook data
          schema:
            $ref: '#/definitions/Quicklook'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # Data download
  /download/{id}:
    x-swagger-object-key: id
    x-swagger-router-view: DownloadView
    get:
      operationId: Download
      summary: Download data
      tags:
        - Measurements
      description: |
        This endpoint allows to get a quicklook of certain data measurement.
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: Raw data
          schema:
            $ref: '#/definitions/RawData'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  # testing multiaction endpoint
  /data/{id}/{action}:
    x-swagger-router-view: DownloadData
    get:
      summary: Download data
      tags:
        - Measurements
      description: Single endpoint for two actions. Untested!
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - name: action
          in: path
          type: string
          required: true
          enum:
            - download
            - quicklook
      responses:
        200:
          description: JSON data
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'

# return objects
definitions:
  Project:
    type: object
    properties:
      id:
        type: number
        description: Unique project ID
      name:
        type: string
        description: Name of the project
      desc:
        type: string
        description: Description of the project
      timelapse:
        $ref: '#/definitions/Time'

  Device:
    type: object
    properties:
      id:
        type: number
        description: Unique device ID
      name:
        type: string
        description: Short name of the device
      desc:
        type: string
        description: Detailed info about the device
      channels:
        type: array
        items:
          type: string

  Channel:
    type: object
    properties:
      id:
        type: number
        description: Unique channel ID
      name:
        type: string
        description: Short name of the channel

  Parameter:
    type: object
    properties:
      id:
        type: number
        description: Unique parameter ID
      name:
        type: string
        description: Short name of the parameter
      description:
        type: string
        description: Detailed parameter information
      channel:
        type: string
        description: URL to corresponding channel

  Session:
    type: object
    properties:
      id:
        type: integer
        description: Unique session ID
      project:
        type: integer
        description: Related project ID
      orbit:
        type: number
        description: Orbit representation
      geoline:
        type: string
        description: Where data has been measured
      measurements:
        type: array # api links to measurement instances
        description: Available measurements for this session
        items:
          type: string
      time:
        $ref: '#/definitions/Time'

  Measurement:
    type: object
    properties:
      url:
        description: API URL to certain Measurement
        type: string

  Quicklook:
    type: object
    properties:
      data:
        type: string
        description: Quicklook data

  RawData:
    type: object
    properties:
      data:
        type: string
        description: Raw data

  # Time interval
  Time:
    type: object
    properties:
      begin:
        type: string
      end:
        type: string

  # Error message
  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message
